name: Generate RAG Prompt Analysis Report

on:
  schedule:
    - cron: '0 2 * * *'     # daily at 02:00 UTC
  workflow_dispatch:
    inputs:
      query_limit:
        description: 'Number of queries to process'
        required: false
        default: '1500'
      prompt_limit:
        description: 'Number of prompts to process'
        required: false
        default: '200'

concurrency:
  group: rag-report
  cancel-in-progress: true

jobs:
  rag-report:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TOPK: '3'
      EMBED_ONLY_THRESHOLD: '0.88'
      CONCURRENCY: '10'
      QUERY_LIMIT: ${{ github.event.inputs.query_limit || '1500' }}
      PROMPT_LIMIT: ${{ github.event.inputs.prompt_limit || '200' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create folders
        run: |
          mkdir -p shared/data
          mkdir -p pro2_RAG_LLM/reports

      - name: Load datasets
        run: |
          echo "Running load_datasets with limit=$QUERY_LIMIT and prompt-limit=$PROMPT_LIMIT"
          python shared/load_datasets.py \
            --queries-out shared/data/queries.csv \
            --prompts-out shared/data/prompts.csv \
            --limit ${QUERY_LIMIT} \
            --prompt-limit ${PROMPT_LIMIT}

      - name: Generate RAG report
        run: |
          python pro2_RAG_LLM/match_RAG_report.py \
            --prompts shared/data/prompts.csv \
            --queries shared/data/queries.csv \
            --out pro2_RAG_LLM/reports/prompt_analysis_$(date +%Y%m%d).xlsx

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rag-report-${{ github.run_number }}
          path: |
            pro2_RAG_LLM/reports/*.xlsx
            shared/data/*.csv
          retention-days: 90
