name: Generate Prompt Analysis Report

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      query_limit:
        description: 'Number of queries to process'
        required: false
        default: '5000'
      prompt_limit:
        description: 'Number of prompts to process'
        required: false
        default: '200'
      project:
        description: 'Which project to run (1, 2, or both)'
        required: false
        default: 'both'
        type: choice
        options:
          - '1'
          - '2'
          - 'both'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p shared/data
        mkdir -p pro1_LLM_only/data pro1_LLM_only/reports
        mkdir -p pro2_RAG_LLM/data pro2_RAG_LLM/reports

    - name: Load datasets
      run: |
        python shared/load_datasets.py \
          --queries-out shared/data/queries.csv \
          --prompts-out shared/data/prompts.csv \
          --limit ${{ github.event.inputs.query_limit || '5000' }} \
          --prompt-limit ${{ github.event.inputs.prompt_limit || '200' }}

    - name: Generate Project 1 report (LLM Only)
      if: ${{ github.event.inputs.project == '1' || github.event.inputs.project == 'both' || github.event.inputs.project == '' }}
      run: |
        python pro1_LLM_only/match_and_report.py \
          --prompts shared/data/prompts.csv \
          --queries shared/data/queries.csv \
          --out pro1_LLM_only/reports/prompt_analysis_$(date +%Y%m%d).xlsx \
          --model gpt-4o-mini

    - name: Generate Project 2 report (RAG + LLM)
      if: ${{ github.event.inputs.project == '2' || github.event.inputs.project == 'both' || github.event.inputs.project == '' }}
      run: |
        python pro2_RAG_LLM/match_and_report.py \
          --prompts shared/data/prompts.csv \
          --queries shared/data/queries.csv \
          --out pro2_RAG_LLM/reports/prompt_analysis_$(date +%Y%m%d).xlsx \
          --model gpt-4o-mini

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prompt-reports-${{ github.run_number }}
        path: |
          pro1_LLM_only/reports/*.xlsx
          pro2_RAG_LLM/reports/*.xlsx
          shared/data/*.csv
        retention-days: 90
